[tool.ruff]
target-version = "py39"
fix = true
cache-dir = ".ruff_cache"
include = ["*.py"]
preview = true
line-length = 120

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = "."
python_files = "test_*.py"