name: Build
on:
  workflow_call:

jobs:
  build-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.9

      - name: Cache pip downloads
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ hashFiles('requirements.txt') }}

      - name: Cache virtualenv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: venv
          key: venv-${{ hashFiles('requirements.txt') }}
      
      - name: Install dependencies into ./venv
        if: steps.cache-venv.outputs.cache-hit != 'true'
        shell: bash
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt pytest ruff
        