name: Tests

on:
  push:
    paths:
      - "**.py"
  pull_request:
    paths:
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.13.1
      uses: actions/setup-python@v5
      with:
        python-version: 3.13.1
        cache: 'pip'
    - run: |
        pip install pytest
        pip install -r requirements.txt

    - name: Run pytest
      run: PYTHONPATH=. pytest 
