name: Tests

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.9

    - name: Cache venv
      uses: actions/cache@v4
      with:
        path: venv
        key: venv-${{ hashFiles('requirements.txt') }}
        
    - name: Run pytest
      run: |
        source venv/bin/activate
        pytest 
