name: TypeChecking

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.13.1
      uses: actions/setup-python@v5
      with:
        python-version: 3.13.1

    - name: Download venv artifact
      uses: actions/download-artifact@v4
      with:
        name: python-venv

    - name: Extract and activate venv
      shell: bash
      run: |
        tar -xzf venv.tar.gz
        source venv/bin/activate

    - name: Run mypy
      run: ./venv/bin/mypy --explicit-package-bases src
