name: TypeChecking

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.13.1
      uses: actions/setup-python@v5
      with:
        python-version: 3.13.1

    - name: Cache venv
      uses: actions/cache@v4
      with:
        path: venv
        key: venv-${{ hashFiles('requirements.txt') }}

    - name: Run mypy
      run: |
        source venv/bin/activate
        mypy --explicit-package-bases src
